import {
  Workspace,
  Transaction,
  UdhaarRecord,
  Anomaly,
  Scenario,
  Recommendation,
  CreditReadiness,
  TaxPreview,
} from "@/types/domain";
import { createMoneyFromRupees } from "@/lib/domain/money";

export const WORKSPACES: Workspace[] = [
  {
    id: "sme-bilal",
    kind: "sme",
    name: "Bilal General Store",
    displayName: "Bilal General Store (Kiryana SME)",
    description: "Retail grocery & FMCG distribution — Lahore (Hero Demo)",
    currency: "PKR",
    timezone: "Asia/Karachi",
    features: ["cash_flow", "upload_review", "udhaar_ledger", "simulator", "reports", "credit_readiness", "tax_preview"],
  },
  {
    id: "student-ayesha",
    kind: "student",
    name: "Ayesha Noor",
    displayName: "Ayesha Noor (FAST University)",
    description: "Hostel budget, allowance & freelance tutoring",
    currency: "PKR",
    timezone: "Asia/Karachi",
    features: ["cash_flow", "upload_review", "simulator", "reports"],
  },
  {
    id: "household-khan",
    kind: "household",
    name: "Khan Family",
    displayName: "Khan Family Household",
    description: "Salaried household, utility bills & education planning",
    currency: "PKR",
    timezone: "Asia/Karachi",
    features: ["cash_flow", "upload_review", "simulator", "reports", "tax_preview"],
  },
  {
    id: "enterprise-indus",
    kind: "enterprise",
    name: "Indus Textiles Ltd.",
    displayName: "Indus Textiles (Multi-branch)",
    description: "Spinning & weaving roll-up across Lahore, Faisalabad, Karachi",
    currency: "PKR",
    timezone: "Asia/Karachi",
    features: ["cash_flow", "upload_review", "udhaar_ledger", "simulator", "reports", "credit_readiness", "tax_preview"],
  },
];

/* =========================================================================
   1. SME: Bilal General Store (Hero Demo)
========================================================================= */

export const SME_STARTING_BALANCE = createMoneyFromRupees(420000); // Rs. 420,000

export const SME_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-sme-1",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-08",
    merchant: "Engro Foods Distributor",
    amount: createMoneyFromRupees(125000),
    direction: "outflow",
    category: "Inventory Restock",
    confidence: 0.96,
    reviewStatus: "confirmed",
    sourceRef: "INV-ENG-9821.pdf",
  },
  {
    id: "tx-sme-2",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-07",
    merchant: "Daily Retail Counter Cash Inflow",
    amount: createMoneyFromRupees(86500),
    direction: "inflow",
    category: "Retail Sales",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "POS-BATCH-1007",
  },
  {
    id: "tx-sme-3",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-06",
    merchant: "Unilever Pakistan Wholesale",
    amount: createMoneyFromRupees(94000),
    direction: "outflow",
    category: "Inventory Restock",
    confidence: 0.94,
    reviewStatus: "confirmed",
    sourceRef: "INV-UNI-5542.pdf",
  },
  {
    id: "tx-sme-4",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-05",
    merchant: "Shan Foods Distribution Hub",
    amount: createMoneyFromRupees(42500),
    direction: "outflow",
    category: "Inventory Restock",
    confidence: 0.91,
    reviewStatus: "confirmed",
    sourceRef: "INV-SHAN-1109.pdf",
  },
  {
    id: "tx-sme-5",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-04",
    merchant: "LESCO Commercial Electricity Bill",
    amount: createMoneyFromRupees(38600),
    direction: "outflow",
    category: "Utilities",
    confidence: 0.98,
    reviewStatus: "confirmed",
    sourceRef: "BILL-LESCO-OCT26.pdf",
  },
  {
    id: "tx-sme-6",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-03",
    merchant: "Easypaisa Merchant QR Settlement",
    amount: createMoneyFromRupees(54200),
    direction: "inflow",
    category: "Digital Payments",
    confidence: 0.97,
    reviewStatus: "confirmed",
    sourceRef: "EP-SETTLE-883",
  },
  {
    id: "tx-sme-7",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-02",
    merchant: "National Foods Spices & Condiments",
    amount: createMoneyFromRupees(48000),
    direction: "outflow",
    category: "Inventory Restock",
    // Hero low-confidence row for OCR/extraction review demo:
    confidence: 0.62,
    reviewStatus: "needs_review",
    sourceRef: "SCAN-RECEIPT-4029.jpg",
  },
  {
    id: "tx-sme-8",
    workspaceId: "sme-bilal",
    occurredAt: "2026-10-01",
    merchant: "Shop Rent - Main Market Johar Town",
    amount: createMoneyFromRupees(75000),
    direction: "outflow",
    category: "Rent & Facilities",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "RENT-RECEIPT-OCT",
  },
];

export const SME_UDHAAR: UdhaarRecord[] = [
  {
    id: "udh-1",
    workspaceId: "sme-bilal",
    customerName: "Tariq Mahmood (Al-Madina Caterers)",
    phone: "0300-8451290",
    issuedAt: "2026-07-15",
    dueAt: "2026-08-15",
    outstanding: createMoneyFromRupees(85000),
    status: "overdue",
    ageBucket: "90d+",
    sourceRef: "KATA-LEAF-041",
    notes: "Ordered wedding ghee & basmati bulk; promise date missed twice.",
  },
  {
    id: "udh-2",
    workspaceId: "sme-bilal",
    customerName: "Imran Butt (Butt Sweets)",
    phone: "0321-4458921",
    issuedAt: "2026-08-10",
    dueAt: "2026-09-10",
    outstanding: createMoneyFromRupees(65000),
    status: "overdue",
    ageBucket: "60d",
    sourceRef: "KATA-LEAF-089",
    notes: "Dairy restock; agreed to pay in two installments.",
  },
  {
    id: "udh-3",
    workspaceId: "sme-bilal",
    customerName: "Chaudhry Akram Farm Supplies",
    phone: "0333-5120934",
    issuedAt: "2026-08-28",
    dueAt: "2026-09-28",
    outstanding: createMoneyFromRupees(50000),
    status: "overdue",
    ageBucket: "30d",
    sourceRef: "KATA-LEAF-114",
    notes: "Monthly ration for farm workers.",
  },
  {
    id: "udh-4",
    workspaceId: "sme-bilal",
    customerName: "Dr. Farooq Clinic Staff Ration",
    phone: "0302-9988112",
    issuedAt: "2026-09-25",
    dueAt: "2026-10-25",
    outstanding: createMoneyFromRupees(42000),
    status: "current",
    ageBucket: "30d",
    sourceRef: "KATA-LEAF-150",
    notes: "Regular 30-day corporate settlement account.",
  },
  {
    id: "udh-5",
    workspaceId: "sme-bilal",
    customerName: "Master Aslam (School Canteen)",
    phone: "0314-2201944",
    issuedAt: "2026-09-18",
    dueAt: "2026-10-18",
    outstanding: createMoneyFromRupees(38000),
    status: "current",
    ageBucket: "30d",
    sourceRef: "KATA-LEAF-162",
    notes: "Biscuits & juices canteen credit.",
  },
  {
    id: "udh-6",
    workspaceId: "sme-bilal",
    customerName: "Haji Usman Tea Stall",
    phone: "0345-6677881",
    issuedAt: "2026-07-20",
    dueAt: "2026-08-20",
    outstanding: createMoneyFromRupees(35000),
    status: "overdue",
    ageBucket: "90d+",
    sourceRef: "KATA-LEAF-033",
    notes: "Milk powder & sugar weekly credit.",
  },
];

export const SME_ANOMALIES: Anomaly[] = [
  {
    id: "anom-sme-1",
    workspaceId: "sme-bilal",
    kind: "supplier_price",
    severity: "warning",
    title: "Supplier Price Increase (+18.4%) Detected",
    explanation: "Engro Foods invoice unit cost for 16kg Cooking Oil tin increased from Rs. 7,600 to Rs. 9,000 without prior vendor notice.",
    amount: createMoneyFromRupees(22400),
    period: "October 2026 vs September 2026",
    transactionIds: ["tx-sme-1"],
    sourceRefs: ["INV-ENG-9821.pdf"],
    detectedAt: "2026-10-08",
  },
  {
    id: "anom-sme-2",
    workspaceId: "sme-bilal",
    kind: "overdue_udhaar",
    severity: "critical",
    title: "Overdue Udhaar Exceeds Working Capital Buffer",
    explanation: "Rs. 235,000 of customer Udhaar is overdue past 30 days. Collecting top 3 debtors would extend cash runway by 38 days.",
    amount: createMoneyFromRupees(235000),
    period: "Last 90 days aging",
    transactionIds: [],
    sourceRefs: ["KATA-LEAF-041", "KATA-LEAF-089", "KATA-LEAF-114"],
    detectedAt: "2026-10-09",
  },
  {
    id: "anom-sme-3",
    workspaceId: "sme-bilal",
    kind: "spike",
    severity: "info",
    title: "Seasonal Peak: Spices & Marinades Outflow (+35%)",
    explanation: "Shan Foods & National Foods purchases rose before wedding season rush. Historical turnover indicates stock clears within 21 days.",
    amount: createMoneyFromRupees(31000),
    period: "First week October",
    transactionIds: ["tx-sme-4", "tx-sme-7"],
    sourceRefs: ["INV-SHAN-1109.pdf", "SCAN-RECEIPT-4029.jpg"],
    detectedAt: "2026-10-07",
  },
];

export const SME_SCENARIO: Scenario = {
  id: "scen-sme",
  workspaceId: "sme-bilal",
  title: "SME Working Capital Stress Test",
  description: "Evaluate cash runway under realistic Pakistani supply chain shocks and test recovery levers.",
  shocks: [
    {
      id: "shock_price_rise",
      kind: "price_rise",
      label: "Supplier Wholesale Price Rise (+15%)",
      description: "Edible oil and dairy FMCG distributors announce 15% wholesale tariff increases.",
      percent: 15,
      active: true,
    },
    {
      id: "shock_delayed_udhaar",
      kind: "delayed_receivables",
      label: "Top 3 Overdue Customers Delay by 45 Days",
      description: "Rs. 200,000 in overdue receivables remains uncollected during harvest/wedding lull.",
      amount: createMoneyFromRupees(200000),
      delayDays: 45,
      active: true,
    },
    {
      id: "shock_utility_spike",
      kind: "utility_spike",
      label: "Summer / Peak Fuel Electricity Spike",
      description: "LESCO peak billing and commercial fuel adjustment adds Rs. 25,000 / month.",
      amount: createMoneyFromRupees(25000),
      active: false,
    },
  ],
  recoveryActions: [
    {
      id: "collect_udhaar",
      label: "Collect Top 3 Receivables (FIFO 70% settlement)",
      description: "Offer a 2% prompt cash discount to Tariq Caterers, Butt Sweets, and Akram Farms to collect Rs. 140,000 immediately.",
      estimatedImpact: createMoneyFromRupees(140000),
      active: false,
    },
    {
      id: "defer_stock",
      label: "Defer Discretionary Bulk Stock Purchase",
      description: "Postpone high-inventory slow-moving spice orders by 21 days, saving immediate cash drain.",
      estimatedImpact: createMoneyFromRupees(85000),
      active: false,
    },
  ],
  assumptions: [
    "Baseline run-rate: Rs. 1,450,000 monthly sales / Rs. 1,320,000 monthly supplier outflows",
    "Shortage threshold: Rs. 0 (operating cash exhaust)",
    "Calculations are strictly deterministic based on daily rate deltas",
  ],
};

export const SME_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-sme-1",
    workspaceId: "sme-bilal",
    title: "Initiate structured recovery on Rs. 150,000 overdue Udhaar",
    plainReason: "Tariq Caterers and Butt Sweets have exceeded 60-day terms. Recovering even 60% eliminates the projected Day 42 cash dip.",
    estimatedImpact: createMoneyFromRupees(90000),
    timeHorizon: "Next 14 days",
    evidenceTransactionIds: [],
    evidenceSourceRefs: ["KATA-LEAF-041", "KATA-LEAF-089"],
    assumptions: ["Assumes 60% recovery via WhatsApp reminder and partial installment offer"],
    category: "collections",
  },
  {
    id: "rec-sme-2",
    workspaceId: "sme-bilal",
    title: "Consolidate Engro Oil & Ghee orders to unlock 3.5% distributor rebate",
    plainReason: "Weekly fragmented orders of 16kg tins miss the 50-tin bulk distributor discount tier.",
    estimatedImpact: createMoneyFromRupees(26250),
    timeHorizon: "Next 30 days",
    evidenceTransactionIds: ["tx-sme-1"],
    evidenceSourceRefs: ["INV-ENG-9821.pdf"],
    assumptions: ["Order 50 tins bi-weekly instead of 15 tins weekly"],
    category: "supplier",
  },
  {
    id: "rec-sme-3",
    workspaceId: "sme-bilal",
    title: "Set up merchant QR QR-code on front counter to reduce manual cash reconciliation",
    plainReason: "Easypaisa settlements cleared within 12 hours with zero cash leakage vs counter cash discrepancies.",
    estimatedImpact: createMoneyFromRupees(15000),
    timeHorizon: "Next 30 days",
    evidenceTransactionIds: ["tx-sme-6"],
    evidenceSourceRefs: ["EP-SETTLE-883"],
    assumptions: ["Converts 20% of counter cash to direct wallet receipts"],
    category: "cash_flow",
  },
];

export const SME_CREDIT_READINESS: CreditReadiness = {
  workspaceId: "sme-bilal",
  overallScore: 78,
  factors: [
    {
      name: "Cash Buffer & Reserve Coverage",
      score: 82,
      weight: 35,
      status: "good",
      details: "Current balance provides 97 days runway against fixed non-inventory expenses.",
    },
    {
      name: "Supplier Invoice Settlement Consistency",
      score: 85,
      weight: 25,
      status: "good",
      details: "All distributor invoices paid within 14-day trade credit window.",
    },
    {
      name: "Receivable Collection Turnaround",
      score: 62,
      weight: 25,
      status: "moderate",
      details: "Average debtor aging is 48 days (recommended benchmark is under 30 days).",
    },
    {
      name: "Utility & Tax Filing Record",
      score: 75,
      weight: 15,
      status: "good",
      details: "Commercial LESCO meter on-time payment track record across 12 billing cycles.",
    },
  ],
  isShariahCompliantWording: true,
  disclaimer: "Illustrative readiness score for SME financing programs. Does not constitute credit underwriting or official approval.",
};

export const SME_TAX_PREVIEW: TaxPreview = {
  workspaceId: "sme-bilal",
  taxYear: "TY 2026-2027",
  estimatedGrossInflow: createMoneyFromRupees(17400000), // Annualized Rs. 17.4M
  totalExpenses: createMoneyFromRupees(15840000),
  deductibleExpenses: createMoneyFromRupees(14600000),
  estimatedTaxableIncome: createMoneyFromRupees(2800000),
  illustrativeEstimatedTax: createMoneyFromRupees(325000),
  deductibleCategories: [
    {
      category: "Cost of Goods Sold (Verified Supplier Invoices)",
      spent: createMoneyFromRupees(13200000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(13200000),
      note: "Fully allowable under Section 20 of Income Tax Ordinance with documented invoices.",
    },
    {
      category: "Commercial Shop Rent & Municipal Charges",
      spent: createMoneyFromRupees(900000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(900000),
      note: "Rent paid via banking channel with withholding challan.",
    },
    {
      category: "Commercial Utilities (LESCO & PTCL)",
      spent: createMoneyFromRupees(500000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(500000),
      note: "Commercial sales tax and income tax advance adjustments available on utility bills.",
    },
  ],
  disclaimer: "Preliminary Estimate — FBR Validation Required. Not certified tax advice.",
};

/* =========================================================================
   2. Student: Ayesha Noor
========================================================================= */

export const STUDENT_STARTING_BALANCE = createMoneyFromRupees(28500);

export const STUDENT_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-stu-1",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-01",
    merchant: "Monthly Family Stipend",
    amount: createMoneyFromRupees(35000),
    direction: "inflow",
    category: "Family Allowance",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "BANK-TRF-MBL-1001",
  },
  {
    id: "tx-stu-2",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-02",
    merchant: "FAST Hostel Mess Fee",
    amount: createMoneyFromRupees(18000),
    direction: "outflow",
    category: "Hostel & Food",
    confidence: 0.98,
    reviewStatus: "confirmed",
    sourceRef: "HOSTEL-CHALLAN-09",
  },
  {
    id: "tx-stu-3",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-04",
    merchant: "Online Programming Tutoring Stipend",
    amount: createMoneyFromRupees(10000),
    direction: "inflow",
    category: "Tutoring Freelance",
    confidence: 0.95,
    reviewStatus: "confirmed",
    sourceRef: "JAZZCASH-RCV-441",
  },
  {
    id: "tx-stu-4",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-05",
    merchant: "Urdu Bazaar Textbooks & Printouts",
    amount: createMoneyFromRupees(4500),
    direction: "outflow",
    category: "Books & Study",
    confidence: 0.88,
    reviewStatus: "confirmed",
    sourceRef: "RCP-BOOK-229",
  },
  {
    id: "tx-stu-5",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-06",
    merchant: "Jazz Monthly Super Duper Data Card",
    amount: createMoneyFromRupees(2200),
    direction: "outflow",
    category: "Mobile & Internet",
    confidence: 0.97,
    reviewStatus: "confirmed",
    sourceRef: "JAZZ-SCRATCH-OCT",
  },
  {
    id: "tx-stu-6",
    workspaceId: "student-ayesha",
    occurredAt: "2026-10-07",
    merchant: "Campus Cafeteria & Chai",
    amount: createMoneyFromRupees(3800),
    direction: "outflow",
    category: "Food & Social",
    confidence: 0.65,
    reviewStatus: "needs_review",
    sourceRef: "CAFE-CASH-OCT",
  },
];

export const STUDENT_ANOMALIES: Anomaly[] = [
  {
    id: "anom-stu-1",
    workspaceId: "student-ayesha",
    kind: "spike",
    severity: "info",
    title: "Semester Start Academic Expenses (+60%)",
    explanation: "Course packs and lab manuals concentrated in week 1. Routine semester expense pattern.",
    amount: createMoneyFromRupees(4500),
    period: "First week October",
    transactionIds: ["tx-stu-4"],
    sourceRefs: ["RCP-BOOK-229"],
    detectedAt: "2026-10-06",
  },
];

export const STUDENT_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-stu-1",
    workspaceId: "student-ayesha",
    title: "Lock Rs. 5,000 in digital micro-savings wallet before month-end",
    plainReason: "Freelance tutoring income provides a 22% monthly surplus. Putting it in a locked digital pot prevents incidental cafe spending.",
    estimatedImpact: createMoneyFromRupees(5000),
    timeHorizon: "This month",
    evidenceTransactionIds: ["tx-stu-3"],
    evidenceSourceRefs: ["JAZZCASH-RCV-441"],
    assumptions: ["Locks tutoring inflow into 0-cost digital pocket"],
    category: "cash_flow",
  },
  {
    id: "rec-stu-2",
    workspaceId: "student-ayesha",
    title: "Switch to Campus EduRoam Wi-Fi to lower mobile data reload",
    plainReason: "Mobile data card costs Rs. 2,200/mo. Activating student Wi-Fi credentials reduces data needs by 50%.",
    estimatedImpact: createMoneyFromRupees(1100),
    timeHorizon: "Next 30 days",
    evidenceTransactionIds: ["tx-stu-5"],
    evidenceSourceRefs: ["JAZZ-SCRATCH-OCT"],
    assumptions: ["Lowers mobile package to base student bundle"],
    category: "cash_flow",
  },
];

/* =========================================================================
   3. Household: Khan Family
========================================================================= */

export const HOUSEHOLD_STARTING_BALANCE = createMoneyFromRupees(185000);

export const HOUSEHOLD_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-hh-1",
    workspaceId: "household-khan",
    occurredAt: "2026-10-01",
    merchant: "Corporate Monthly Salary Credit",
    amount: createMoneyFromRupees(350000),
    direction: "inflow",
    category: "Salary",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "SALARY-SLIP-SEP26.pdf",
  },
  {
    id: "tx-hh-2",
    workspaceId: "household-khan",
    occurredAt: "2026-10-03",
    merchant: "The City School Monthly Tuition (2 Children)",
    amount: createMoneyFromRupees(74000),
    direction: "outflow",
    category: "Education",
    confidence: 0.98,
    reviewStatus: "confirmed",
    sourceRef: "TCS-CHALLAN-9011.pdf",
  },
  {
    id: "tx-hh-3",
    workspaceId: "household-khan",
    occurredAt: "2026-10-04",
    merchant: "Metro Cash & Carry Monthly Grocery",
    amount: createMoneyFromRupees(62000),
    direction: "outflow",
    category: "Groceries",
    confidence: 0.95,
    reviewStatus: "confirmed",
    sourceRef: "METRO-RCP-7712",
  },
  {
    id: "tx-hh-4",
    workspaceId: "household-khan",
    occurredAt: "2026-10-06",
    merchant: "LESCO Domestic Electricity (Summer Rate)",
    amount: createMoneyFromRupees(58500),
    direction: "outflow",
    category: "Utilities",
    confidence: 0.97,
    reviewStatus: "confirmed",
    sourceRef: "LESCO-DOM-8941",
  },
  {
    id: "tx-hh-5",
    workspaceId: "household-khan",
    occurredAt: "2026-10-07",
    merchant: "SNGPL Gas & PTCL Flash Fiber",
    amount: createMoneyFromRupees(12500),
    direction: "outflow",
    category: "Utilities",
    confidence: 0.93,
    reviewStatus: "confirmed",
    sourceRef: "BILL-SNGPL-PTCL",
  },
  {
    id: "tx-hh-6",
    workspaceId: "household-khan",
    occurredAt: "2026-10-08",
    merchant: "Car Fuel & Maintenance",
    amount: createMoneyFromRupees(28000),
    direction: "outflow",
    category: "Transport",
    confidence: 0.72,
    reviewStatus: "needs_review",
    sourceRef: "PSO-CARD-552",
  },
];

export const HOUSEHOLD_ANOMALIES: Anomaly[] = [
  {
    id: "anom-hh-1",
    workspaceId: "household-khan",
    kind: "spike",
    severity: "warning",
    title: "Electricity Bill Spike (+42%) Above Autumn Average",
    explanation: "LESCO domestic peak billing units triggered slab tariff increase. Shift to winter baseline will ease outflow by Nov 15.",
    amount: createMoneyFromRupees(18000),
    period: "September-October billing cycle",
    transactionIds: ["tx-hh-4"],
    sourceRefs: ["LESCO-DOM-8941"],
    detectedAt: "2026-10-07",
  },
];

export const HOUSEHOLD_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-hh-1",
    workspaceId: "household-khan",
    title: "Claim Section 60D advance tax deduction for school tuition",
    plainReason: "Withholding tax deducted on The City School fee challan is adjustable against salaried tax return on IRIS portal.",
    estimatedImpact: createMoneyFromRupees(37000),
    timeHorizon: "Annual Tax Return",
    evidenceTransactionIds: ["tx-hh-2"],
    evidenceSourceRefs: ["TCS-CHALLAN-9011.pdf"],
    assumptions: ["Section 60D adjustable tax under FBR rules for tuition fees"],
    category: "tax",
  },
  {
    id: "rec-hh-2",
    workspaceId: "household-khan",
    title: "Switch bulk non-perishables to wholesale club monthly buying",
    plainReason: "Split grocery spending between neighborhood stores and Metro reduces unit packaging premium.",
    estimatedImpact: createMoneyFromRupees(8500),
    timeHorizon: "Monthly",
    evidenceTransactionIds: ["tx-hh-3"],
    evidenceSourceRefs: ["METRO-RCP-7712"],
    assumptions: ["12% average basket savings on pantry staples"],
    category: "cash_flow",
  },
];

/* =========================================================================
   4. Enterprise: Indus Textiles Ltd.
========================================================================= */

export const ENTERPRISE_STARTING_BALANCE = createMoneyFromRupees(14800000);

export const ENTERPRISE_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-ent-1",
    workspaceId: "enterprise-indus",
    occurredAt: "2026-10-02",
    merchant: "Export Letter of Credit (LC) Settlement - UK Buyer",
    amount: createMoneyFromRupees(18500000),
    direction: "inflow",
    category: "Export Sales",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "LC-HBL-EXP-0881.pdf",
  },
  {
    id: "tx-ent-2",
    workspaceId: "enterprise-indus",
    occurredAt: "2026-10-04",
    merchant: "Raw Cotton Ginning Consignment (Faisalabad Hub)",
    amount: createMoneyFromRupees(12400000),
    direction: "outflow",
    category: "Raw Material",
    confidence: 0.97,
    reviewStatus: "confirmed",
    sourceRef: "INV-GIN-FSD-301.pdf",
  },
  {
    id: "tx-ent-3",
    workspaceId: "enterprise-indus",
    occurredAt: "2026-10-06",
    merchant: "K-Electric & SSGC Industrial Energy Tariff",
    amount: createMoneyFromRupees(6200000),
    direction: "outflow",
    category: "Industrial Power",
    confidence: 0.96,
    reviewStatus: "confirmed",
    sourceRef: "KE-BILL-IND-9910.pdf",
  },
  {
    id: "tx-ent-4",
    workspaceId: "enterprise-indus",
    occurredAt: "2026-10-07",
    merchant: "Staff Payroll Disbursement (420 Factory Technicians)",
    amount: createMoneyFromRupees(8900000),
    direction: "outflow",
    category: "Factory Payroll",
    confidence: 0.99,
    reviewStatus: "confirmed",
    sourceRef: "HBL-PAYROLL-OCT.xlsx",
  },
  {
    id: "tx-ent-5",
    workspaceId: "enterprise-indus",
    occurredAt: "2026-10-08",
    merchant: "Specialized Reactive Dyes & Pigments Import",
    amount: createMoneyFromRupees(3400000),
    direction: "outflow",
    category: "Chemicals & Processing",
    confidence: 0.68,
    reviewStatus: "needs_review",
    sourceRef: "CUSTOMS-GD-8812.pdf",
  },
];

export const ENTERPRISE_UDHAAR: UdhaarRecord[] = [
  {
    id: "udh-ent-1",
    workspaceId: "enterprise-indus",
    customerName: "Gulberg Garments Export Unit",
    phone: "042-35789011",
    issuedAt: "2026-07-01",
    dueAt: "2026-08-01",
    outstanding: createMoneyFromRupees(6800000),
    status: "overdue",
    ageBucket: "90d+",
    sourceRef: "CORP-INV-8810",
    notes: "Batch yarn delivery; awaiting clearance from buyer buyer inspection.",
  },
  {
    id: "udh-ent-2",
    workspaceId: "enterprise-indus",
    customerName: "Mehran Apparel Karachi",
    phone: "021-34567890",
    issuedAt: "2026-08-15",
    dueAt: "2026-09-15",
    outstanding: createMoneyFromRupees(5400000),
    status: "overdue",
    ageBucket: "60d",
    sourceRef: "CORP-INV-9022",
    notes: "Spinning unit delivery.",
  },
  {
    id: "udh-ent-3",
    workspaceId: "enterprise-indus",
    customerName: "Ravi Home Textiles",
    phone: "041-8899001",
    issuedAt: "2026-09-20",
    dueAt: "2026-10-20",
    outstanding: createMoneyFromRupees(6200000),
    status: "current",
    ageBucket: "30d",
    sourceRef: "CORP-INV-9150",
    notes: "30-day corporate trade credit.",
  },
];

export const ENTERPRISE_ANOMALIES: Anomaly[] = [
  {
    id: "anom-ent-1",
    workspaceId: "enterprise-indus",
    kind: "supplier_price",
    severity: "critical",
    title: "Industrial Gas Tariff Fuel Charge Surcharge (+22%)",
    explanation: "SSGC industrial tariff revision added Rs. 1,400,000 to spinning unit boiler operations.",
    amount: createMoneyFromRupees(1400000),
    period: "September-October bill",
    transactionIds: ["tx-ent-3"],
    sourceRefs: ["KE-BILL-IND-9910.pdf"],
    detectedAt: "2026-10-07",
  },
];

export const ENTERPRISE_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-ent-1",
    workspaceId: "enterprise-indus",
    title: "Execute trade credit insurance or factoring on Gulberg Garments overdue invoice",
    plainReason: "Rs. 6.8M past 90 days. Discounting with HBL corporate factoring unlocks Rs. 6.1M liquidity within 72 hours.",
    estimatedImpact: createMoneyFromRupees(6100000),
    timeHorizon: "Next 7 days",
    evidenceTransactionIds: [],
    evidenceSourceRefs: ["CORP-INV-8810"],
    assumptions: ["Bank discounting rate 10% on verified enterprise receivables"],
    category: "collections",
  },
  {
    id: "rec-ent-2",
    workspaceId: "enterprise-indus",
    title: "Apply for SBP Export Refinance Scheme (ERF) concessionary rate",
    plainReason: "Export LC turnover qualifies for concessionary 7.5% financing vs KIBOR+3% working capital overdraft.",
    estimatedImpact: createMoneyFromRupees(1200000),
    timeHorizon: "Next quarter",
    evidenceTransactionIds: ["tx-ent-1"],
    evidenceSourceRefs: ["LC-HBL-EXP-0881.pdf"],
    assumptions: ["State Bank of Pakistan Part-II ERF facility eligibility"],
    category: "cash_flow",
  },
];

export const ENTERPRISE_CREDIT_READINESS: CreditReadiness = {
  workspaceId: "enterprise-indus",
  overallScore: 84,
  factors: [
    {
      name: "Debt Service Coverage Ratio (DSCR)",
      score: 88,
      weight: 35,
      status: "good",
      details: "Operating EBITDA covers corporate facility payments 2.4x.",
    },
    {
      name: "Export LC Turnover & State Bank Compliance",
      score: 92,
      weight: 25,
      status: "good",
      details: "Full E-Form tracking and transparent FX proceeds repatriation.",
    },
    {
      name: "Customer Concentration & Aging Risk",
      score: 72,
      weight: 25,
      status: "moderate",
      details: "3 buyers represent 65% of domestic trade receivables.",
    },
    {
      name: "FBR Corporate Active Taxpayer Status",
      score: 85,
      weight: 15,
      status: "good",
      details: "Audit-cleared ATL standing with continuous monthly withholding statements.",
    },
  ],
  isShariahCompliantWording: false,
  disclaimer: "Illustrative corporate credit health indicator for bank consortium financing.",
};

export const ENTERPRISE_TAX_PREVIEW: TaxPreview = {
  workspaceId: "enterprise-indus",
  taxYear: "TY 2026-2027",
  estimatedGrossInflow: createMoneyFromRupees(580000000),
  totalExpenses: createMoneyFromRupees(506000000),
  deductibleExpenses: createMoneyFromRupees(478000000),
  estimatedTaxableIncome: createMoneyFromRupees(74000000),
  illustrativeEstimatedTax: createMoneyFromRupees(21460000),
  deductibleCategories: [
    {
      category: "Cotton & Yarn Raw Materials",
      spent: createMoneyFromRupees(340000000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(340000000),
      note: "Section 21 compliant banking transactions with registered ginners.",
    },
    {
      category: "Industrial Power & Captive Generation",
      spent: createMoneyFromRupees(75000000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(75000000),
      note: "Full sales tax input adjustment and deductible expense.",
    },
    {
      category: "Plant & Machinery Depreciation Allowance",
      spent: createMoneyFromRupees(45000000),
      deductiblePercentage: 100,
      deductibleAmount: createMoneyFromRupees(45000000),
      note: "Third Schedule accelerated initial allowance on new looms.",
    },
  ],
  disclaimer: "Preliminary Estimate — FBR Validation Required. Subject to Corporate Tax Return audit.",
};
